# Generated by Django 5.1.6 on 2025-04-07 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('kcalPer100g', models.IntegerField(blank=True, null=True)),
                ('proteinPer100g', models.FloatField(blank=True, null=True)),
                ('carbsPer100g', models.FloatField(blank=True, null=True)),
                ('fatPer100g', models.FloatField(blank=True, null=True)),
                ('fiberPer100g', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_weight', models.IntegerField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal')),
            ],
        ),
        migrations.CreateModel(
            name='CountedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('parentMeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal')),
            ],
        ),
        migrations.CreateModel(
            name='WeightedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('parentFood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.food')),
            ],
        ),
    ]
