# Generated by Django 5.1.6 on 2025-03-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('kcalPer100g', models.IntegerField(blank=True, null=True)),
                ('proteinPer100g', models.IntegerField(blank=True, null=True)),
                ('carbsPer100g', models.IntegerField(blank=True, null=True)),
                ('fatPer100g', models.IntegerField(blank=True, null=True)),
                ('fiberPer100g', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('protein', models.IntegerField(blank=True, null=True)),
                ('carbs', models.IntegerField(blank=True, null=True)),
                ('fat', models.IntegerField(blank=True, null=True)),
                ('fiber', models.IntegerField(blank=True, null=True)),
                ('parentFood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.food')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('foods', models.ManyToManyField(to='main.weightedfood')),
            ],
        ),
    ]
