# Generated by Django 5.1.7 on 2025-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='grams_per_piece',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='grams_per_tablespoon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='grams_per_teaspoon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightedfood',
            name='measurement_type',
            field=models.CharField(choices=[('grams', 'Grams'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon'), ('piece', 'Piece')], default='grams', max_length=50),
        ),
    ]
