# Generated by Django 5.1.6 on 2025-04-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_food_carbsper100g_alter_food_fatper100g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='kcalPer100g',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
