# Generated by Django 5.1.7 on 2025-05-23 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food_grams_per_piece_food_grams_per_tablespoon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAndMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('food', 'Food'), ('meal', 'Meal')], max_length=50)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.food')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.meal')),
            ],
        ),
    ]
