# Generated by Django 5.1.6 on 2025-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_food_kcalper100g'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
